// Client
export {
  createSupabaseClient,
  createBrowserClient,
  createServerClient,
  isSupabaseConfigured,
} from "./client";
export type { SupabaseClientInstance } from "./client";

// Types
export type {
  KspClient,
  KspClientStatus,
  KspClientInsert,
  KspClientUpdate,
  KspLicense,
  KspPlanType,
  KspLicenseStatus,
  KspLicenseInsert,
  KspLicenseUpdate,
  KspDevice,
  KspDeviceInsert,
  KspDeviceUpdate,
  KspUser,
  KspUserRole,
  KspUserInsert,
  KspUserUpdate,
  KspApp,
  KspAppStatus,
  KspAppCategory,
  KspAppFeature,
  KspAppInsert,
  KspAppUpdate,
  KspTransaction,
  KspTransactionType,
  KspTransactionStatus,
  KspTransactionInsert,
  KspTransactionUpdate,
  KspLog,
  KspLogAction,
  KspLogLevel,
  KspLogInsert,
  KspSetting,
  KspSettingValueType,
  KspSettingUpdate,
  KspSite,
  KspSiteTheme,
  KspSiteNavItem,
  KspSiteSocial,
  KspSitePage,
  KspSiteContentBlock,
  KspSiteSettings,
  KspSiteInsert,
  KspSiteUpdate,
  KspSitePageInsert,
  KspSitePageUpdate,
  KspShareMission,
  KspShareMissionType,
  KspShareMissionStatus,
  KspShareMissionInsert,
  KspShareMissionUpdate,
  KspShareLog,
  KspShareMethod,
  KspShareLogInsert,
} from "./types";

// Queries
export {
  getClients,
  getClientById,
  createClient,
  updateClient,
  getLicenses,
  getLicenseById,
  getLicenseByKey,
  createLicense,
  updateLicense,
  revokeLicense,
  getDevices,
  getDeviceByFingerprint,
  bindDevice,
  unbindDevice,
  updateDevice,
  touchDevice,
  countActiveDevices,
  getUsers,
  getUserById,
  getUserByEmail,
  createUser,
  updateUser,
  recordUserLogin,
  getApps,
  getAppByCode,
  getAppById,
  createApp,
  updateApp,
  getTransactions,
  getTransactionById,
  createTransaction,
  updateTransaction,
  verifyTransaction,
  getLogs,
  createLog,
  logInfo,
  logError,
  getSettings,
  getSetting,
  getSettingValue,
  updateSettings,
  updateSettingByKey,
  bulkUpdateSettings,
  getShareMissions,
  getShareMissionsByType,
  createShareMission,
  updateShareMission,
  logShare,
  getShareCount,
  getShareLogs,
  canStartNewMission,
  getCompletedMissionCount,
  isBackupUnlocked,
  getActiveMission,
} from "./queries";
